{% set name = "lidar" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2e0d87bd0de15298849950e64abcf3c83df8c27ee6e1bd249f6940b18c7b4a0

build:
  number: 0
  entry_points:
    - lidar=lidar.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click >=6.0
    - gdal
    - gdown
    - geopandas
    - matplotlib-base
    - numpy
    # - pysimplegui
    - python >={{ python_min }}
    - rasterio
    - richdem
    - scikit-image
    - scipy
    - pyshp
    - whitebox

test:
  requires:
    - python {{ python_min }}
  imports:
    - numpy
  # commands:
  #   - lidar --help

about:
  home: https://github.com/giswqs/lidar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for delineating nested surface depressions from digital elevation data
  doc_url: https://lidar.gishub.org
  dev_url: https://github.com/giswqs/lidar

extra:
  recipe-maintainers:
    - giswqs
