{% set name = "lidar" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 440d00e5788968473f0fd18a1724ec15a47d2f596385b8e7dd3d67ec99d048bb

build:
  number: 0
  entry_points:
    - lidar=lidar.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click >=6.0
    - matplotlib-base
    - numpy
    - pysimplegui
    - python
    - richdem
    - scikit-image
    - scipy
    - gdal
    - pyshp
    - whitebox

test:
  imports:
    - lidar
  commands:
    - lidar --help

about:
  home: https://github.com/giswqs/lidar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for delineating nested surface depressions from digital elevation data
  doc_url: https://lidar.gishub.org
  dev_url: https://github.com/giswqs/lidar

extra:
  recipe-maintainers:
    - giswqs
